/*
 * Copyright 2026 The Vantix Authors
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package dev.vantix.codegen;

import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.TypeSpec;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/** Renders {@link TypeSpec}s into {@link GeneratedFile}s with Vantix's fixed, deterministic layout. */
final class Sources {

    /**
     * First line of every regenerated file. {@link SourceWriter} only ever deletes files that start
     * with it, so a user's own source can never be removed as "stale".
     */
    static final String MARKER = "// Generated by Vantix from schema.vx.";

    private static final String HEADER = MARKER.substring(3) + " Do not edit: this file is rewritten on every build.";

    private Sources() {}

    static AnnotationSpec generatedAnnotation() {
        return AnnotationSpec.builder(JavaTypes.GENERATED)
                .addMember("value", "$S", "dev.vantix")
                .build();
    }

    static GeneratedFile generated(String packageName, TypeSpec type) {
        JavaFile file = JavaFile.builder(packageName, type)
                .addFileComment("$L", HEADER)
                .skipJavaLangImports(true)
                .indent("    ")
                .build();
        return new GeneratedFile(packageName, type.name(), normalize(file.toString()), false);
    }

    static GeneratedFile scaffold(String packageName, TypeSpec type) {
        JavaFile file = JavaFile.builder(packageName, type)
                .skipJavaLangImports(true)
                .indent("    ")
                .build();
        return new GeneratedFile(packageName, type.name(), normalize(file.toString()), true);
    }

    private static String normalize(String source) {
        return tidy(source.replace("\r\n", "\n"));
    }

    private static final int MAX_LINE = 100;
    private static final Pattern ANNOTATION_OPEN = Pattern.compile("^(\\s*)@[\\w.]+\\($");
    private static final Pattern ENUM_GAP = Pattern.compile(",\n\n(    [A-Z][A-Z0-9_]*[,\n])");

    /**
     * JavaPoet puts every member of a field annotation on its own line and separates enum constants
     * with blank lines. Both are noise in code people read, so annotations that fit in
     * {@value #MAX_LINE} columns are collapsed onto one line, and enum constants are kept together.
     * Purely cosmetic and deterministic.
     */
    static String tidy(String source) {
        String[] lines = source.split("\n", -1);
        List<String> out = new ArrayList<>(lines.length);
        for (int i = 0; i < lines.length; i++) {
            Matcher open = ANNOTATION_OPEN.matcher(lines[i]);
            if (open.matches()) {
                String close = open.group(1) + ")";
                int end = i + 1;
                while (end < lines.length && !lines[end].equals(close)) {
                    end++;
                }
                if (end < lines.length) {
                    StringBuilder joined = new StringBuilder(lines[i]);
                    for (int j = i + 1; j < end; j++) {
                        joined.append(j == i + 1 ? "" : " ").append(lines[j].strip());
                    }
                    joined.append(')');
                    if (joined.length() <= MAX_LINE) {
                        out.add(joined.toString());
                        i = end;
                        continue;
                    }
                }
            }
            out.add(lines[i]);
        }
        String result = String.join("\n", out);
        String previous;
        do {
            previous = result;
            result = ENUM_GAP.matcher(result).replaceAll(",\n$1");
        } while (!result.equals(previous));
        return result;
    }
}
